### ISSUE TITLE
can i set

### ISSUE THREAD

**Issue by azl397985856** [yalishizhude/api-mock#3]
my project architecture covered data server and login server. 
but can't set the login server address, because api-document limit to input address that starting with '/'
![image](https://cloud.githubusercontent.com/assets/12479470/14909756/97311c02-0e19-11e6-8fc9-146339d699a5.png)

my loging server adderss is http:// 10.45.10.125

**Comment by yalishizhude** [comment]
Login server and interface test server should be the same host~

**Comment by azl397985856** [comment]
okay . now i decide to use nginx  to split the request into different servers
