### ISSUE TITLE
how can i set the request data into the mongo

### ISSUE THREAD

**Issue by azl397985856** [yalishizhude/api-mock#4]
now i've  edited my data, and i want to save to mongoDB so that i can fetch it next time .  what should i do ?

**Comment by azl397985856** [comment]
i wanna know whether it supported or maybe i should extend it

**Comment by yalishizhude** [comment]
when you finished editing the interface , you should click the right button at the bottom to save it. 
![image](https://cloud.githubusercontent.com/assets/3870098/15133751/8f63f620-1698-11e6-9ddc-f01766192d1d.png)

**Comment by azl397985856** [comment]
sorry,  that's not what i mean .  
i sended a request to interface A, the payload {a: "1234"} for example
how can i save the data to db.  and next time call interface A . i can get the same result .
and further more, i can update the fetched result, so next time i call interface A, i wanna get the updated data

**Comment by yalishizhude** [comment]
The server cannot save requests and requests' param,so you have to make another call with `{a:"1234"}` to get the result.

**Comment by azl397985856** [comment]
ok thank u anyway
i decide to rewrite the mock module to save changes .

**Comment by yalishizhude** [comment]
Why do you have this request? I'm curious about the situation.
为什么你有这个需求呢？我很好奇你这是什么样的业务场景~

**Comment by azl397985856** [comment]
我有这样一个场景
1.根据type 获取配置信息  
参数是{type: 'a'}  返回结果是{name: 'name', type: 'a'}
参数是{type: 'b'}  返回结果是{name: 'name', type: 'b'}
2.更新配置信息
参数是{name: 'name', type: 'new'}  返回结果也是{name: 'name', type: 'new'}
我想下次请求的时候还是new，这样我就和真正请求后台没有区别了

**Comment by yalishizhude** [comment]
这个牵涉到业务逻辑了，建议使用mockjs模板来实现：
`{"name": "name", "type|1": ["a", "b"]}`
这样会随机返回
`{"name": "name", "type": "a"}`
或
`{"name": "name", "type": "b"}`

**Comment by azl397985856** [comment]
好的。 谢谢~~~不过 我还是重新下你的逻辑实现吧。
