### ISSUE TITLE
关于项目打包

### ISSUE THREAD

**Issue by azl397985856** [yalishizhude/api-mock#5]
不知道你有没有打算提供一个script 可以将应用打包成静态文件呢？
就像 npm run build
然后打出一个html  ，js ，css 等，可以通过静态服务器去发布呢

**Comment by yalishizhude** [comment]
@azl397985856 
你这个需求场景是什么？
mock服务器是不需要页面的，只负责响应接口返回假数据~

**Comment by azl397985856** [comment]
是这样的。 我和api-document集成的时候，想要把api-document 和 mock 一起打包放到服务器上去。所以需要打包。 如果您能提供接口服务器的打包的话就更好了。

**Comment by azl397985856** [comment]
这样我就可以通过静态服务器管理我的项目了。

**Comment by yalishizhude** [comment]
没太明白...
你的意思是把api-document和api-mock合并成一个项目，同时部署吗？

**Comment by azl397985856** [comment]
分开部署的。就算mock不需要界面，应该也是要打包的吧。。。还是说要把源码服务器放上去，安装node，然后npn run start 启动？？？

**Comment by yalishizhude** [comment]
1. git clone 源码
2. cd到项目目录，`npm install`
3. `npm start`启动即可

**Comment by azl397985856** [comment]
这种方式发布吗？

**Comment by yalishizhude** [comment]
嗯，直接把源码部署到服务器，然后安装依赖之后启动即可使用~

看来我还是得补个教程~( ╯□╰ )

**Comment by azl397985856** [comment]
这样哦~~  ^_^好吧  谢谢
